spring:
  application:
    name: deck-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      name: deck-service
      profile: default
      label: main