spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/v2/cards/**,/api/v2/decks/*/cards/**

        - id: deck-service
          uri: lb://deck-service
          predicates:
            - Path=/api/v2/decks/**

        - id: deck-service.api-docs
          uri: lb://deck-service
          predicates:
            - Path=/deck-service/v3/api-docs
          filters:
            - RewritePath=/deck-service/v3/api-docs, /v3/api-docs

        - id: card-service.api-docs
          uri: lb://card-service
          predicates:
            - Path=/card-service/v3/api-docs
          filters:
            - RewritePath=/card-service/v3/api-docs, /v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Card API
        url: /card-service/v3/api-docs
      - name: Deck API
        url: /deck-service/v3/api-docs

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    metadata-map:
      prometheus:
        path: /actuator/prometheus

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
