spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      prometheus:
        path: /actuator/prometheus

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

server:
  port: 8888