spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/cards
      uuid-representation: standard

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 0