spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/cards
      uuid-representation: standard

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    metadata-map:
      prometheus:
        path: /actuator/prometheus

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

server:
  port: 0

springdoc:
  swagger-ui:
    enabled: false

messaging:
  consumer:
    deck-deleted:
      name: deck.deleted
      dlq: deck.deleted.dlq
      dlx: deck.deleted.dlx
  producer:
    card-deleted:
      name: card.deleted
      dlq: card.deleted.dlq
      dlx: card.deleted.dlx
    card-created:
      name: card.created
      dlq: card.created.dlq
      dlx: card.created.dlx
