spring:
  datasource:
    url: jdbc:postgres://localhost:5432/decks
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    metadata-map:
      prometheus:
        path: /actuator/prometheus

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

server:
  port: 0

springdoc:
  swagger-ui:
    enabled: false

messaging:
  consumer:
    card-deleted:
      name: card.deleted
      dlq: card.deleted.dlq
      dlx: card.deleted.dlx
  producer:
    deck-deleted:
      name: deck.deleted
      dlq: deck.deleted.dlq
      dlx: deck.deleted.dlx