spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/decks
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    metadata-map:
      prometheus:
        path: /actuator/prometheus
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

server:
  port: 0

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    title: Deck API
    description: Deck Service API documentation
    url: http://localhost:8080